version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    commands:
      cp ./settings.xml /root/.m2/settings.xml
      # - command
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
      mvn clean install
      # - command
  post_build:
    commands:
        mvn deploy
      # - command
#artifacts:
  #files:
    # - location
    # - location
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths